Feature/ex 3
AlexHurray/NYTimes pull request #2
Opened 2018-10-08 09:30 UTC by AlexHurray

Ex 3. without CollapsingToolbarLayout

2018-10-10 10:20 UTC, colriot requested changes

2018-10-10 10:20 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/ItemDecorationNewsList.java
> +    private int mSizeGridSpacingPx;
Если затаскиваешь код извне всё равно приводи его к общему стилю в проекте. Наименование переменных и тд

2018-10-10 10:20 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/NewsListActivity.java
> +        recyclerView.setLayoutManager(isPortraitOrientation() ?
`?` и `:` в начале строки оставляй. Так же, как и `.` при переносе цепочных вызовов методов

2018-10-10 10:20 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/NewsListActivity.java
> +    @Subscribe(threadMode = ThreadMode.MAIN)
Давай убирать EventBus. Паттерн легко может превратиться в порочное использование - в большом проекте не проследишь, что откуда прилетает. Мы вообще сейчас максимально средствами рассмотренного на лекции будем стараться обходиться. ButterKnife ещё куда ни шло - там всё просто руками переписать и я уверен, что ты уже понимаешь, что и для чего заменяется на ButterKnife

2018-10-10 10:20 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/NewsRecyclerAdapter.java
> +        inflater = LayoutInflater.from(context);
Красивее писать в одном стиле - если есть `this` на других полях, то и тут для стройности добавляй

2018-10-10 10:20 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/NewsRecyclerAdapter.java
> +                inflater.inflate(getLayoutResByViewType(viewType), parent, false)
Сделай длинну строки 120 символов в настройках, поместится тогда строка в одну?

2018-10-10 10:20 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/NewsRecyclerAdapter.java
> +        return (viewType == 2) ? R.layout.news_item_criminal : R.layout.news_item;
Если на самом деле всего два ViewType, то и отдавай всего два разных значения. А логика выяснения ViewType (по Id) пусть будет локализована в методе с соответствующим названием - getItemViewType. 
Кстати, можешь сразу layoutId юзать в качестве viewType

2018-10-10 10:20 UTC, colriot commented on app/src/main/res/layout-land/activity_news_details.xml
> +    <ImageView
А нужна ли нам картинка всё время на самом видном месте? Или всё-таки текст новости - самое важное, и стоит картинку тоже скроллить? Дизайн, бесспорно, на твоё усмотрение, но задумываться о UX я всё равно буду вас заставлять ;)

2018-10-10 10:20 UTC, colriot commented on app/src/main/res/layout-land/activity_news_details.xml
> +    <ImageView
Может быть тут важнее подумать о том, какие паддинги проставить для альбомной ориентации?

2018-10-10 10:20 UTC, colriot commented on app/src/main/res/layout/news_item.xml
> +<?xml version="1.0" encoding="utf-8"?>
Лучше префикс `item_` ставить на первое место, как `activity_`

2018-10-10 10:20 UTC, colriot commented on app/src/main/res/values-ru-rRU/strings.xml
>  <?xml version="1.0" encoding="utf-8"?>
Папку переименуй в `values-ru`, а то будет только на русском в России, но не в Казахстане, Белорусии и тд. Зашейся только на язык, но без страны

2018-10-10 10:20 UTC, colriot commented on app/src/main/res/values/dimens.xml
> +    <dimen name="text_category_size">20sp</dimen>
Также вынеси на первое место весь общий префикс `text_size_`, как `spacing_`, например. Чтобы всё сразу ясно было

2018-10-10 10:20 UTC, colriot commented on build.gradle
> +        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
Зачем? Используй стабильную версию ButterKnife из стандартной репы. Снапшоты - это dev-версия, нестабильная, в разработке.

2018-10-10 10:35 UTC, AlexHurray commented on build.gradle
> +        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
Стабильная не захотела работать с androidx =(

2018-10-10 10:36 UTC, AlexHurray commented on build.gradle
> +        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
Изначально там была стабильная, но решил перейти на androidx, как на лекции советовали

2018-10-14 17:53 UTC, colriot requested changes

2018-10-14 17:53 UTC, colriot commented on app/build.gradle
> +    implementation "androidx.recyclerview:recyclerview:1.0.0"
У всех либ Android Jet (AndroidX) общая версия, т.е. тут то же самое, что и в `cardview` и `appcompat`. Используй ту же переменную.

2018-10-14 17:53 UTC, colriot commented on app/build.gradle
> +    implementation "com.jakewharton:butterknife:9.0.0-SNAPSHOT"
Кстати, RC вышла недавно

2018-10-14 17:53 UTC, colriot commented on app/src/main/AndroidManifest.xml
>      package="com.example.ermolaenkoalex.NYTimes">
Пакеты принято именовать маленькими буквами

2018-10-14 17:53 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/about/AboutActivity.java
> -        applyLayoutMargins4TextView(copyright);
А метод остался?

2018-10-14 17:53 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/about/AboutActivity.java
> +public class AboutActivity extends AppCompatActivity {
Ещё, кстати, хорошая практика выделить `BaseActivity` для твоего кода. Туда удобно, например, вставить логи так, чтобы все твои активити сразу это изменение подхватили. Более практический пример: `ButterKnife.bind` в одном месте, в базовом классе. Только его надо будет поместить в `onContentChanged` метод, который вызывается в конце любого `setConentView`

2018-10-14 17:53 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/ItemDecorationNewsList.java
> +    private boolean mNeedLeftSpacing = false;
А тут префикс остался

2018-10-14 17:53 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/ItemDecorationNewsList.java
> +        int itemPosition = ((RecyclerView.LayoutParams) view.getLayoutParams()).getViewAdapterPosition();
Позицию надо получать из параметра `state`. Потому что тебе нужна позиция в LayoutManager, а не в Adapter

2018-10-14 17:53 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/NewsListActivity.java
> +    private final NewsRecyclerAdapter.OnItemClickListener clickListener = newsItem
Можно и прямо в место вызова ставить (заинлайнить) или сделат ьлокальной переменной.  Делать полем класса ни к чему, когда лишь один раз юзается

2018-10-14 17:53 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/NewsListActivity.java
> +                isPortraitOrientation() ? 1 : NUM_COL_LAND));
`isPortraitO..` можно один раз посчитать, сохранить в переменную и переиспользовать

2018-10-14 17:53 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/NewsRecyclerAdapter.java
> +        this.context = context;
Обычно инициализацию проводят в порядке указания параметров конструктора

2018-10-14 17:53 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/NewsRecyclerAdapter.java
> +        if (newsItems.get(position).getCategory().getId() == 2) {
Сделай 2 именованной константой. А то так кто-то другой или ты (через 2 месяца) вернёшься к этому коду и не вспомнит назначение этого magic number

2018-10-14 17:53 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/NewsRecyclerAdapter.java
> +        public void bind(@NonNull NewsItem newsItem) {
По-моему здесь и в конструкторе `public` не нужен. Всегда старайся минимально-допустимую видимость задавать сущностям. И не расширять её бездумно, оценивать, правильно ли повышать видимость той или иной сущности именно для твоей конкретной задачи или лучше как-то иначе поступить

2018-10-14 17:53 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/utils/StringUtils.java
> +                MINUTE_IN_MILLIS, WEEK_IN_MILLIS, flags).toString();
Если будешь возвращать `СharSequence`, то `toString` можно убрать

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/layout-h500dp-land/activity_profile.xml
> +        android:layout_weight="1">
Если отформатируешь код, то `layout_*` атрибуты будут все сверху. Не забывай форматировать код перед коммитом

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/layout-h500dp-land/activity_profile.xml
> +                tools:ignore="ContentDescription" />
Лучше вместо игнора явно задавать `@null`

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/layout-h500dp-land/activity_profile.xml
> +                tools:ignore="ContentDescription" />
Показывая, что ты не просто забил, а явно там он пустой. 
Коммент относится ко всем таким кускам в коде

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/layout-h700dp/activity_profile.xml
>      android:layout_width="match_parent"
А зачем отдельный layout для определённой "высоты"?

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/layout-land/activity_profile.xml
> +                tools:ignore="UseCompoundDrawables">
Стоило обратить внимание на этот ворнинг и способ его решения. Попробуй использовать вместо LL и отдельного ImageView, атрибуты drawableStart и drawablePadding у TV

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/layout-land/activity_profile.xml
> +                android:textAppearance="@style/standardButtonStyle"
Стили с большой буквы

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/layout/activity_news_list.xml
> +    android:paddingStart="@dimen/spacing_small"
А внизу не нужен паддинг?

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/layout/item_news.xml
> +        android:layout_gravity="start"
Лучше сделать width `match_parent` и layout_gravity убрать (те более, что оно и без него к старту прилепает). Потому что у тебя От ширины текста будет зависеть положение картинки. Если текст не будет раздвигать на всю ширину элемент, то картинка будет не о правому краю.

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/layout/item_news.xml
> +    android:id="@+id/card_news_item"
Реально нужен?

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/layout/item_news_criminal.xml
> +        android:layout_gravity="start"
Та же история

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/layout/item_news_criminal.xml
> +</androidx.cardview.widget.CardView>
Старайся оставлять пустые строки в конце файлов. Тогда не будет вот таких красных маркеров в конце файла и дифы при изменении последних строчек не будут выглядеть стрёмно (с лишней подсвеченной строкой)

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/values/dimens.xml
> +    <dimen name="text_size_category">20sp</dimen>
Не нужно заводить несколько разных переменных под одно и то же значение. Можно в разных стилях использовать одно и то же значение размера, пока реально размер не изменится (по дизайну) и не придётся реально новый размер иметь в ресурсах

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/values/dimens.xml
>      <dimen name="text_size">16sp</dimen>
Просто текст сайз непонятно чего

2018-10-14 17:53 UTC, colriot commented on app/src/main/res/values/dimens.xml
>      <dimen name="image_size">300dp</dimen>
Предлагаю `size_` вынести префиксом, так же, как и с `text_size_`

2018-10-14 17:53 UTC, colriot commented on build.gradle
> +        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
Ага, есть такое. BK зашивается на пакеты View, на которых навешены аннотации. А это `android.enableJetifier=true` не может исправить...

2018-10-14 19:47 UTC, AlexHurray commented on app/src/main/res/layout/item_news.xml
> +    android:id="@+id/card_news_item"
Ты про id'шник?

2018-10-15 12:04 UTC, AlexHurray commented on app/src/main/res/layout-h700dp/activity_profile.xml
>      android:layout_width="match_parent"
Да там и для отдельной ширины не нужны уже сейчас - после нескольких изменений они стали отличаться только ScrollView. Удалю

2018-10-15 12:33 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/ItemDecorationNewsList.java
> +        int itemPosition = ((RecyclerView.LayoutParams) view.getLayoutParams()).getViewAdapterPosition();
Вот тут немного не понял. Почему?

2018-10-17 07:26 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/NewsListActivity.java
> +    private final NewsRecyclerAdapter.OnItemClickListener clickListener = newsItem
Вынес в integers.xml для 3 различных ширин экранов.

2018-10-22 12:08 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/mock/DataUtils.java
> +public class DataUtils {
В utils-классах без реальных методов объекта (а только со статическими) также рекомендуется делать приватный дефолтный конструктор (или даже в нём кидать исключение, чтобы даже через рефлексию нельзя было его вызвать). Я этого не сделал в gist-е, знаю, сделал только в примере домашки.

2018-10-22 12:08 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/NYTimes/ui/newslist/ItemDecorationNewsList.java
> +        int itemPosition = ((RecyclerView.LayoutParams) view.getLayoutParams()).getViewAdapterPosition();
Потому что RV сам по себе асинхронный, т.е позиция элемента в адаптере (когда ты обновил данные, и позиция изменилась) и позиция его вью в LayoutManager (реальная позиция вью, соответствующая элементу) могут отличаться - до реального обновления состояния UI, например, анимацией удаления/добавления элементов. Т.к. тут ты работаешь с отрисовкой, то тут нужна позиция вью/вьюхолдера

2018-10-22 12:24 UTC, colriot approved these changes

2018-10-22 12:24 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsRecyclerAdapter.java
> +        final int CRIMINAL_CATEGORY_ID = 2;
Если уж делать константой, то не локальной в методе, чтобы она не инициализировалась каждый раз внутри метода. Но лучше даже вынести это в `DataUtils` или в сам `Category`, потому что это относится именно к данным.

2018-10-22 12:24 UTC, colriot commented on app/src/main/res/layout/content_news_details.xml
> +</LinearLayout>
Пустые строчки в конце файла ;)

2018-10-22 12:24 UTC, colriot commented on app/src/main/res/values-ru-rRU/strings.xml
>  <?xml version="1.0" encoding="utf-8"?>
У меня помечен как Resolved, но папка не переименована. Передумал?

2018-10-22 12:24 UTC, colriot commented on app/src/main/res/values-w520dp/integers.xml
> +    <integer name="landscape_news_columns_count">2</integer>
Судя по логике значений, речь идёт не только про альбомную ориентацию, а просто про ширину экрана. Так что название ресурса не совсем корректно

2018-10-22 12:25 UTC, colriot commented
Внёс несколько предложений и пару замечаний. В целом всё отлично! Можно мёржить 👍

2018-10-22 14:03 UTC, AlexHurray commented
After PR3

2018-10-22 14:08 UTC, AlexHurray commented
Add NewsListActivity + NewsDetailsActivity (ex3)

2018-10-22 14:29 UTC, merged

2018-10-22 14:33 UTC, AlexHurray commented
Close