Implement ex-4(Threads)
AlexHurray/NYTimes pull request #3
Opened 2018-10-23 12:57 UTC by AlexHurray

2018-10-24 22:48 UTC, colriot requested changes

2018-10-24 22:48 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/mock/DataUtils.java
> +    private static final String LOG_TAG = "NYTimes_Log_DataUtils";
Писать общий префикс `NYTimes` необязательно, потому что ты в logcat-е можешь отфильтровать по пакету. Т.е тэги имеет смысл делать в контексте приложения да и только.

2018-10-24 22:48 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/mock/DataUtils.java
> +        catch (InterruptedException ex){
Форматирование...

2018-10-24 22:48 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
> +            viewModel.bind(recyclerView, refresher);
У тебя `bind` и в `onCreate`, и в `onResume` делается - не надо дублировать. По определению эта операция делается один раз и всегда имеет парную `unbind`. Если вдруг добавится какая-то неидемпотентная операция в `bind`, то при отсутствии парного вызова `unbind` могут не освободиться ресурсы/ не очиститься состояния и тд.

2018-10-24 22:48 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
> +            onRefresh();
Не стоит обновление дёргать через коллбек `SwipeRefreshLayout`а. Это именно коллбек реакции на событие UI - у него одна цель и ответственность. А ты добавляешь ему неявную ответственность за старт загрузки данных. Лучше явно тут дёргать вьюмодель, либо (если будет сложнее логика, чем один метод) вынести всё ответственное за загрузку в отдельный метод с говорящим названием, а его уже дёргать и в `onRefresh`, и где ещё надо.

2018-10-24 22:48 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsRecyclerAdapter.java
> +    NewsRecyclerAdapter(@NonNull Context context,
Думаю, если отформатировать, то теперь оба параметра влезут в одну строку.

2018-10-24 22:48 UTC, colriot commented on app/src/main/res/layout/activity_news_list.xml
> +            android:visibility="visible"
Это и так значение по умолчанию

2018-10-24 22:48 UTC, colriot commented on app/src/main/res/values-ru/strings.xml
> +</resources>
Респект!

2018-10-24 22:48 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListViewModel.java
> +        disposable = Observable.fromCallable(DataUtils::generateNews)
Если вдруг уже идёт запрос, то надо сперва отписаться от него, прежде чем запускать новый. Иначе ты потеряешь ссылку на прошлый `disposable` и уже не сможешь отписаться -> потенциальны memory leak, не говоря уже о ненужном запросе.

2018-10-24 22:48 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListViewModel.java
> +    public void bind(RecyclerView recyclerView, SwipeRefreshLayout refresher) {
Хорошо, что логика вынесена из активити, то чёткой связи нет - передаётся просто два виджета в `bind`, в качестве поставщика которых может выступать любой экран. Так что лучше закончить разделение слоёв введением интерфейса, который абстрагирует View (в терминологии MVС\MVP\MVVM-паттернов). Тогда этот интерфейс будет реализован в активити, и он же будет передаваться в метод `bind`. Имеет смысл сделать что-то типа:
```java
interface View {
  void setData
  void showLoading
  void hideLoading
}
```
В этом случае также не будет явных зависимостей VM на андроидные UI-компоненты, что поможет изоляции. И детали реализации отображения данных (какой RV, какой тип адаптера и тд) будут инкапсулированы внутри такого View

2018-10-24 22:48 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListViewModel.java
> +                    ((NewsRecyclerAdapter) recyclerView.getAdapter()).setData(newsItems);
`NewsListViewModel` конечно неявно относится к работе с `NewsRecyclerAdapter`, но такие зависимости лучше делать явными. Чтобы не получилось, что RV будет другой, и адаптер в RV будет стоять совсем другой - тогда будет `ClassCastException`. См. коммент про View (из MV*-паттернов)

2018-10-25 06:02 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/mock/DataUtils.java
> +        catch (InterruptedException ex){
блин, С++ все еще с нами...

2018-10-25 15:06 UTC, colriot reviewed
6! Ещё растём)

2018-10-25 15:06 UTC, colriot commented on app/build.gradle
>      annotationProcessor "com.jakewharton:butterknife-compiler:9.0.0-rc1"
Здесь тоже стоит общую версию вынести в переменные

2018-10-25 15:06 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
>      private final NewsRecyclerAdapter.OnItemClickListener clickListener = newsItem
Если кроме `onCreate` нигде не юзается, то нет смысла в выносе его в поля класса. Можно даже переменную не заводить.

2018-10-25 15:06 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +    private final String LOG_TAG = "NewsListVM";
`static`

2018-10-25 15:06 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +    public void getNews(boolean force) {
Я для примера название `force` привёл, но в данном методе по сигнатуре непонятно, что форсим (приходится смотреть тело метода). Лучше выбрать более говорящее называние метода или параметра (например, `forceReload`), чтобы по целой сигнатуре было всё ясно.

2018-10-25 15:06 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +            disposable.dispose();
Ещё можно обнулить переменную. Я сам, кстати, на `isDisposed` обычно не проверяю. `null` может служить признаком, что цепочки неактивна. Сейчас проверил код, действительно `dispose` идемпотентный, так что в двойном вызове `dispose` ничего страшного.

2018-10-25 15:06 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +                    newsListView.setData(newsItems);
Подписка живёт всю жизнь презентера, а `newsListView`  есть тольок между `bind` и `unbind`. Значит в коллбэке обязательно надо проверять на наличие вью. Если бы не забывал помечать аннотациями `Nullable` и `Nonnull` (где-то есть, где-то нет), то среда бы подсказала.

2018-10-25 15:06 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +                .doOnSubscribe(disposable -> newsListView.showLoading())
Вот тут просто комментарий: если вдруг заметишь, что в таком случае лагает появление лоадера (задерживается), то лучше его вынести из цепочки Rx просто в начало метода. Чтобы он синхронно выполнялся, а не через коллбэк. Так-то там всё без перебрасываний потоков должно выполняться, но теряется время на инициализацию цепочки, подписку и тд, и только после этого вызывается `onSubscribe`. Просто имей в виду

2018-10-25 15:12 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +                .doOnSubscribe(disposable -> newsListView.showLoading())
Понял, запомнил.

2018-10-25 15:14 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +    private final String LOG_TAG = "NewsListVM";
о, и правда...

2018-10-25 15:23 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +                    newsListView.setData(newsItems);
Согласен, косяк. А что надо пометить, чтобы в данном случае ругалась?

2018-10-25 15:31 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +            disposable.dispose();
окей, я тоже у нас на курсах не видел проверку на isDisposed, подумал, может забыли)

2018-10-25 15:36 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
>      private final NewsRecyclerAdapter.OnItemClickListener clickListener = newsItem
так вроде как юзается =)

2018-10-25 15:54 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +            disposable.dispose();
обнуление после dispose() вроде тоже не попадалось

2018-10-25 15:55 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +                    newsListView.setData(newsItems);
Аннотации стараюсь ставить, но периодически забываю(

2018-10-27 12:54 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
>      private final NewsRecyclerAdapter.OnItemClickListener clickListener = newsItem
Где?)

2018-10-27 12:58 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +            disposable.dispose();
Ну, речь о правильном освобождении ресурсов. Если они не нужны (а он не нужны, раз ты его уже задиспоузил), то стоит освободить ссылку, чтобы сборщик мусора (GC) подобрал объект. Конечно, если ты это (диспоуз) делаешь в `onDestroy`, то не надо, после него в скорости вообще вся активити соберётся GC, вместо со всеми внутренностями. Но в общем случае надо.

2018-10-27 12:59 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +                    newsListView.setData(newsItems);
Если `newsListView` пометить, как `Nullable`, то среда/lint будет подсказывать, что нельзя без проверки вызывать у него методы/

2018-10-27 13:11 UTC, colriot reviewed
И, наверное, последние замечания =)

2018-10-27 13:11 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +    private void loadData() {
Отлично 👍 А я вот пропустил

2018-10-27 13:11 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
>      private NewsListView newsListView;
Вот эти поля я имел в виду, когда про аннотации говорил

2018-10-27 13:11 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
>          disposable = Observable.fromCallable(DataUtils::generateNews)
Лучше бы здесь юзать `Single`, кстати. У тебя one-shot (одноразовая) операция. Т.е "потока данных" как такого не будет. Поэтому лучше сразу эту семантику отразить в типах, тогда правильная типизация ещё и подскажет читающему, как этот кусок кода будет себя вести.

2018-10-27 13:11 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
>                  .subscribe(newsItems -> {
И ещё очень важно: никогда не забывай определить обработчик ошибок в Rx-цепочках. Потому что:
1) по умолчанию там будет брошено исключение (и приложение упадёт), даже если ошибка мелкая или ожидаемая
2) часто (в сетевых запросах так точно) ошибки - это нормальный флоу, ожидаемый. Сеть лагает, интернет отваливается, это не исключительная ситуация, а норма, и это надо обрабатывать адекватно

Конкретно тут имеет смысл сигнализировать юзеру, что что-то пошло не так. Например, тостом.

В следующей домашке будет уже чёткая обработка ошибок с ретраем

2018-10-27 13:11 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +                .doFinally(() -> {
Вот и тут тоже путаница, к вопросу о семантике. Ты тут обрабатываешь завершение работы цепочки (`onComplete` или `onError`), а твои данные, по сути, приходят в `onNext` и уже в этом методе надо отобразить данные (скрыв лоадер в том числе). В общем, путаница)

2018-10-27 20:06 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
>      private final NewsRecyclerAdapter.OnItemClickListener clickListener = newsItem
Пардон, почему-то подумал, что этот коммент про презентер и адаптер

2018-10-27 20:07 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +            disposable.dispose();
Понял

2018-10-27 20:10 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
>                  .subscribe(newsItems -> {
Да, я думал про обработчик ошибок, но тут больше оторванная от реальности задача, решил что тут он не нужен пока что. Как раз собирался реализовывать в следубзем ДЗ.

2018-10-27 20:16 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
>      private NewsListView newsListView;
Аннотации поставил, но у меня при этом студия не ругается почему-то(

2018-10-27 21:02 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +                .doFinally(() -> {
А не проще его в 1 месте вывести, чем 2 раза дублировать типа такого?

```
.subscribe(newsItems -> {
                    Log.d(LOG_TAG, "subscribe call in " + Thread.currentThread());

                    if (newsListView != null) {
                        newsListView.hideLoading();
                        newsListView.setData(newsItems);
                    }
                    newsList.clear();
                    newsList.addAll(newsItems);
                }, error -> {
                    Log.d(LOG_TAG, "OnError call");
                    if (newsListView != null) {
                        newsListView.hideLoading();
                        newsListView.showErrorToast();
                    }
                })
```

2018-10-29 13:20 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
>      private NewsListView newsListView;
Давай после лекции проверим. Только не забудь напомнить

2018-10-29 13:20 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
>                  .subscribe(newsItems -> {
Добро 🤝

2018-10-29 13:22 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +                .doFinally(() -> {
А что ты дублировать думаешь? 

Ты же коммент про `Single` прочитал? Этот как продолжение к нему

2018-10-29 19:42 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +                .doFinally(() -> {
> я тут имел ввиду, что мне надо отключить прогресс бар. Либо я это пишу в doFinally() 1 раз, либо в OnSuccess и OnError 2 раза. Разве не лучше в 1 месте вписать?

Зависит от того, как обрабатывать ты хочешь. Если прям одинаковая обработка, то можно и в `doFinally` (а в конкретных обработчиках отдельных случаев ничего уже не писать), но скорее всего, у тебя будет только одна общая строчка `hideLoading`. И экономия на ней будет невелика, а вот то, что она исчезнет из реального места, где обработка Успешного и Неуспешного случаев идёт, может привести к тому, что ты (или коллега, читающие код) не заметишь, что “ещё и это действие будет выполнено“. Т.е в реальности у тебя просто логика обработки Успешного и Неиспешного (каждого) кейсов размажется по двум местам.

2018-10-29 19:58 UTC, colriot approved these changes

2018-10-29 19:59 UTC, merged