Implement ex-5(Networking)
AlexHurray/NYTimes pull request #4
Opened 2018-10-31 20:11 UTC by AlexHurray

2018-11-04 13:21 UTC, colriot reviewed
Добавил пачку комментов. И ты забыл добавить в PR скриншоты новых/обновлённых экранов

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/NetworkAPI/RestApi.java
> +    private static final String URL = "http://api.nytimes.com/svc/topstories/v2/";
Здесь большой разницы нет, т.к тут всего один запрос в АПИ, но вообще больше похоже, что общая часть - это `http://api.nytimes.com/` или `http://api.nytimes.com/svc/`, а `topstories/v2/` - это уже кусок урла, специфичного для конкретного метода.

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/NetworkAPI/RestApi.java
> +
Лишние пустые строки

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/NetworkAPI/RestApi.java
> +    private final NewsEndpoint newsEndpoint;
Опять-таки, с учётом того, что тут всего один метод (а более обще - всего один, новостной, АПИ), то не вижу смысла в выделении отдельного поля и добавления ещё одного метода `.news()` в цепочку вызова сетевого запроса. Но это реально имеет смысл, когда у тебя приложение разбито на фичи, у каждого из которых свой модуль и свой кусок АПИ. Тогда имеет смысл такой кусок АПИ абстрагировать отдельным интерфейсом, чтобы остальные фичи не знали о других.

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/NetworkAPI/NewsEndpoint.java
> +    Single<Response<ResultsDTO>> getNews(@Path("section") @NonNull String section);
Тебе тут именно `Response<ResultsDTO>` нужен или достаточно `ResultsDTO`?

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/mock/DataUtils.java
> +                darwinAwards.getName(),
Так как ты теперь работаешь с реальными данными, то можно эти фейковые уже и удалить

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
> +    public static void start(Activity activity, String url, String category) {
А почему не оставить, как было?

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
> +                Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
👍

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
> +    private static final String NYTIMES_HOST = "www.nytimes.com";
Я бы сделал это константой `WebClient`-а, чтобы не зависело от того, в каком активити используется

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
> +                throw new IllegalArgumentException("Unknown state: " + state);
👍

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
> +            if (Build.VERSION.SDK_INT < 23) {
Лучше заюзать `TextViewCompat.setTextAppearance()`, там за тебя уже верная имплементация вызовется в зависимости от АПИ. И в целом, когда тебе надо разные методы в зависимости от АПИ дёргать, проверяй, нет ли какого `*Compat` класса из компат-библиотек, где это уже реализовано.
Такие разные методы для `View` реализованы во `ViewCompat`, если метод, скажем, `TextView`, то будет в `TextViewCompat` и тд. Это касательно вьюшек. Для других АПИ похожие правила.

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
> +            chip.setText(getString(section.getSectionNameResId()));
Подозреваю, что есть метод для `resId`, где не надо вызывать `getString`

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +    public void getNews(boolean forceReload, String section) {
Делегируй вызов `getNews(boolean)` этому методу тоже. Просто прокидывай текущее значение `currentSection`.

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +    private String currentSection = Section.Home.getSectionName();
Ты везде используешь строки, но со строками теряется строгая типизация. В строку можно передать всякий булшит, её надо как-то сравнивать с другими строками и тд. Используй сам enum! Он прекрасно со всем справится. В том числе в ретрофит-интерфейсе

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +            showState(ResponseState.ServerError);
Почему именно серверная, ведь может быть и клиентская?

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +        final ResultsDTO body = response.body();
Если `GET` запрос выполнился успешно, то у него всегда будет Body.

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +        if (!response.isSuccessful()) {
Ты вообще можешь убрать обработку `Response<T>`, и обрабатывать сразу `T`, в нашем случае `ResultsDTO`. Если ответ будет неуспешным, то будет прокинут error в `Observer.onError`

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/ResponseState.java
> +    HasData,
В enum-e значения - суть константы, поэтому именовать их принято тоже капсом с подчёркиваниями

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/Section.java
> +    Home("home", R.string.section_home),
То же замечание по поводу именования.

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/Section.java
> +    Opinion("opinion", R.string.section_opinion),
А теперь про сам enum. Ты сделал почти правильно. Тут ты руками указал значение (`sectionName`) для каждой категории как поле, но из-за этого тебе приходится везде, где нужно значение, использовать строки, а это плохо с точки зрения типизации и формализации АПИ (не только Rest API, но и АПИ твоих собственных классов). Правильно было бы сделать так:
`@SerializedName("opinion") OPINION(R.string.section_opinion),`

В UI используется тот же самый ресурс, который локализуется. А вот в программном коде используется enum-значение `OPINION`, и теперь ты в переменную `section` не присвоишь произвольную строку, а только одно из заданного набора значений. И благодаря Gson и верной аннотации `SerializedName` ты сможешь тот же enum использовать в Retrofit-интерфейсе, а средствами конвертера он автоматом превратится в нужную строку.

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/dto/ResultDTO.java
> +    private String section;
В итоге и здесь можно будет юзать enum `Section`

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +            newsListView.setData(newsList);
У тебя успешный кейс устанавливается двумя методами: установкой данных и установкой стейта. Очень легко один из них забыть, получается не очень удобное АПИ для этого. Лучше сделать так, чтобы у тебя одним вызовом сеттился и стейт, и данные. Например, две перегрузки метода `showState` с одним и двумя параметрами, или, наоборот, второй метод с названием `showStateWithData` или типа того.

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
> +        switch (state) {
Вообще со стейтом хороший подход, но тут плохо обрабатывается такой случай, когда у тебя совместное состояние, например, если старые данные, и ты хочешь показать ошибку загрузки новых. Т.е не скрыть весь список с данными и показать полноэкранную ошибку, а, например, показать только тост с ошибкой. Поэтому, может иметь смысл в качестве стейта передавать полную картину: есть ли данные?, есть ли ошибка?, есть ли загрузка?. И вычислять этот стейт как раз по результатам очередной операции загрузки с учётом уже имеющихся данных

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/utils/NewsItemConverter.java
> +                , imageUrl
Запятые на той же строке, что и параметр :)

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/utils/NewsItemConverter.java
> +        if (mediaObjects.size() > 2) {
Не стоит заниматься такой оптимизацией, она лишь усложняется код. С учётом того, что набор форматов может меняться и индекс "нашего" может легко сдвинуться. А если он останется вторым, то нам для того, чтобы добраться до него, нужно будет лишь выполнить проверку первого элемента. Т.е +1 проверка элемента и -1 проверка на размер, они не совсем одинаковые по затратам процессорного времени, но тем не менее, примерно то на то и выйдет. А в общем случае даже быстрее будет.

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/utils/NewsItemConverter.java
> +        return multimediaDTO.getType().equalsIgnoreCase(IMAGE_TYPE)
Вместо этого `type` и `format` тоже стоило бы сделать enum-ами. Тогда проверки были бы не строковыми, а проверками на равенство ссылок (т.е объекты-значения в enum-ах синглоны), а информация о типе Multimedia не размазывалась бы ещё и по конвертеру (например, инфа о допустимых значениях полей `type` и `format`).

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/utils/NewsItemConverter.java
> +public class NewsItemConverter {
Если это просто utils-класс только со статикой, то не забывай делать класс и конструктор `final`.

2018-11-04 13:21 UTC, colriot commented on app/src/main/res/layout/activity_news_list.xml
> +
Пустой тэг можно схлопнуть

2018-11-04 13:21 UTC, colriot commented on app/src/main/res/layout/activity_news_list.xml
> +                android:id="@+id/tv_no_data"
Не забывай и тут правильные паддинги расставлять, чтобы не получился текст на другом размере экрана под самые края.

2018-11-04 13:21 UTC, colriot commented on app/src/main/res/layout/activity_news_list.xml
> +                android:id="@+id/tv_error"
Также, с учетом одинаковых визуально вьюх, совсем необязательно держать их две разных. Можно сэкономить и в коде устанавливать разный текст в зависимости от ошибки.

2018-11-04 13:21 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
> +            chip.setOnClickListener(view -> presenter.getNews(true, section.getSectionName()));
А как это будет выглядеть визуально? Можно ли отключить фильтр по секции?

2018-11-04 14:01 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
> +            chip.setText(getString(section.getSectionNameResId()));
И правда есть...

2018-11-04 18:00 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/dto/ResultDTO.java
> +    private String section;
Там может прийти больше 21 значения из Enum'a. + Они приходят с большой буквы, так что не выйдет(

2018-11-04 18:10 UTC, AlexHurray commented
![image](https://user-images.githubusercontent.com/37106193/47968056-9deab400-e075-11e8-8bb1-9379e9de778d.png)
![image](https://user-images.githubusercontent.com/37106193/47968094-0cc80d00-e076-11e8-9d5a-29003e8ef6f4.png)

![image](https://user-images.githubusercontent.com/37106193/47968076-c5418100-e075-11e8-80c4-1d93f2bd3119.png)
![image](https://user-images.githubusercontent.com/37106193/47968098-19e4fc00-e076-11e8-826d-ee083a56ab1b.png)

2018-11-04 18:11 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
> +            chip.setOnClickListener(view -> presenter.getNews(true, section.getSectionName()));
Нет, потому что для api обязательно должна быть задана секция. По умолчанию это Home

2018-11-04 18:32 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListActivity.java
> +            chip.setOnClickListener(view -> presenter.getNews(true, section.getSectionName()));
Как выглядит приложил ниже

2018-11-04 20:00 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +    public void getNews(boolean forceReload, String section) {
Сделал так, так как хотел чтобы не обновлялось при повторном нажатии на одну и ту же категорию, но обновлялось при рефреше и первом запуске. Сейчас подумал и решил что это лишнее и надо обновлять при нажатии на любой chip.

2018-11-07 10:36 UTC, colriot commented
Возможно стоит сделать нефиксированную высоту карточки и использовать `StaggeredGridAdapter`

2018-11-07 11:08 UTC, colriot reviewed
Ещё добавлю:
> Сделал так, так как хотел чтобы не обновлялось при повторном нажатии на одну и ту же категорию, но обновлялось при рефреше и первом запуске. Сейчас подумал и решил что это лишнее и надо обновлять при нажатии на любой chip.

В принципе, можно это же флагом `forceRefresh` решать. Если не force и одинаковые `section` и `currentSection`, то не обновляем

2018-11-07 11:08 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/NetworkAPI/EnumValueConverter.java
> +        Converter<Enum, String> converter = null;
Можно сделать даже лаконичнее, без временной переменной. В `if`-е сразу возвращать значение, а в самом конце просто `return null`

2018-11-07 11:08 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/NetworkAPI/RestApi.java
> +    public static synchronized NewsEndpoint getInstance() {
Метод `getInstance` должен по логике возвращать инстанс этого самого класса. А у тебя метод лежит в `RestApi`, а возвращает `NewsEndpoint`. Либо оставь, как было - это не критично (главное задумываться, что и почему ты делаешь), либо переименуй метод (например, в `newsApi()` или тот же `news()`) и возвращай оттуда уже `NewsEndpoint`. Важно то, что тебе не нужен `sRestApi` больше, в реальности достаточно хранить только конечный endpoint, т.к он единственный.

2018-11-07 11:08 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/ContentFormat.java
> +    @SerializedName("Standard Thumbnail") ST_THUMBNAIL,
Атас у них типы...

2018-11-07 11:08 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/ContentFormat.java
> +public enum ContentFormat {
Я бы посоветовал назвать это `MultimediaFormat` и `MultimediaType`, потому что глобально контент у тебя - это новости. И не совсем понятно название к чему привязано

2018-11-07 11:08 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +            newsListView.setData(data);
В этом кусочке, по сути, ничего не поменялось. На стейт теперь шире, но (!) данные - это тоже часть состояния. То есть в итоге тебе нужно три поля: `boolean isLoading`, `Data data`, `Error error` (имена типов для примера). А `hasData` и `hasError` уже вычисляются. И тогда у тебя только один метод у вью будет `showState` (рендеринг состояния UI)

2018-11-07 11:08 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/utils/NewsItemConverter.java
> +        if (type != null && type == ContentType.IMAGE) {
`type != null` лишнее. enum можно сравнивать с `null` 👍

2018-11-07 11:08 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/utils/NewsItemConverter.java
> +        return type != null && type == ContentType.IMAGE && format != null && format == ContentFormat.THUMB_LARGE;
Проверки на `null` излишни

2018-11-07 11:08 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
> +        startIntent.putExtra(KEY_URL, newsItem.getItemUrl());
В смысле, в целом, почему нельзя было передавать туда целую новость?) В следующем задании все равно там будет `id`, понятно. Но мне хотелось понять смысл.

2018-11-07 11:36 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
> +        startIntent.putExtra(KEY_URL, newsItem.getItemUrl());
В смысле, в целом, почему нельзя было передавать туда целую новость?) В следующем задании все равно там будет id, понятно. Но мне хотелось понять смысл. - чтобы меньше запихивать в bundle. Конечно 1 мб не занять, но все же наверное лучше пихать меньше, разве нет?

2018-11-07 11:41 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/ContentFormat.java
> +public enum ContentFormat {
Ок, долго пытался правильное название найти, но че-то это как раз и не пришло в голову почему-то

2018-11-07 14:25 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
> +        startIntent.putExtra(KEY_URL, newsItem.getItemUrl());
Serializable с модели убрал

2018-11-07 17:31 UTC, colriot reviewed
Ещё немного замечаний

2018-11-07 17:31 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/NetworkAPI/RestApi.java
> +        final Retrofit retrofit = buildRetrofitClient(httpClient);
Получилась практически типичная схема с DI :)

2018-11-07 17:31 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsRecyclerAdapter.java
> +        if (newsItems.get(position).getCategory().equalsIgnoreCase(CATEGORY_US)) {
И снова мы опустились до сравнения строк - это вот прям плохо. Если ты где-то начинается сравнивать строки не для работы со строками/подстроками, а чтобы определить тип/подтип данных и тд, то знай, что ты скорее всего идёшь по неверному пути. Если тебе в UI-модели нужно понимание, как отображать её, лучше всего добавить явный признак. `isUsSection()` или `hasWideUi()` и тд. 
Итого: если ты используешь в UI прямо модельки из сети, то используй прямо значения enum (или если от них зависит не один параметр "какой отображать лейаут", а много, то тоже имеет смысл его оставить), либо, если ты используешь отдельные UI-модели (PresentationModel), где уже готовые для отображения данные лежат (только бери и сеть в отдельные вьюшки), то заводи прям специальный признак (уже готовые для отображения данные) "показывать так или эдак".

2018-11-07 17:31 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/ResponseState.java
> +    private Integer errorMessageId;
Не обязательно использовать класс-обёртку. Можно сравнивать с 0. Нулевых resourceId никогда не бывает (это даже используется в коде SDK)

2018-11-07 17:31 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/ResponseState.java
>      public void setErrorMessage(@IdRes int errorMessage) {
Сеттер не нужен. Объект по сути иммутабельный, конструируй его сразу в конструкторе (просто сделай нужные оверлоады), чтобы потом при передаче его куда-либо, его никто промежуточный не мог поменять.

2018-11-07 17:31 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/utils/NewsItemConverter.java
> +        MultimediaType type = multimediaDTO.getType();
Можешь их даже заинлайнить, в принципе

2018-11-07 18:52 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/ResponseState.java
> +    private Integer errorMessageId;
супер

2018-11-07 19:41 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsRecyclerAdapter.java
> +        if (newsItems.get(position).getCategory().equalsIgnoreCase(CATEGORY_US)) {
Смотри... section и subsection(который может быть пустым) в ответе, это нифига не тот же section, который пропихивается в get-запрос.(т.е. в запросе nyregion, а в section будет "u.s.") И у меня нет списка их возможных значений. Я правильно понимаю, что мне надо в любом случае сравнивать строки? Я могу сделать isUsSection(), но там мне все равно придется сравнивать строки, я прав?

2018-11-09 09:13 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +        int errorMessageId = (throwable instanceof IOException) ? R.string.error_network : R.string.error_request;
Проверь, обязательны ли скобки

2018-11-09 09:13 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/ResponseState.java
> +            this.data.addAll(data);
Можно просто присвоить, чтобы избежать дополнительного копирования данных.

2018-11-09 09:18 UTC, colriot requested changes
Вот это очень важно про потоки и конвертацию

2018-11-09 09:18 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +                .subscribe(this::checkResponseAndShowState, this::handleError);
Вот тут внутри у тебя происходит конвертация. И происходит она на UI-потоке. Это плохо, потому что может быть сделана в бэкграунде, и может быть достаточно весома при больших данных.
Так что надо добавить операцию `.map` в цепочку, по переключения на Main-тред

2018-11-10 22:15 UTC, colriot approved these changes
Два замечания по RxJava остались. Всё остальное отлично - примерно так обычно это и работает 👍 Исправляй, скинь мне глянуть (на всякий), но сам мёрж и продолжай с 6м

2018-11-10 22:15 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +            return null;
Есть такой нюанс, в RxJava2 нельзя эмиттить/генерировать `null` в качестве элемента. Т.ч надо явно пустой список тут передать, если это ОК ситуация, или явную ошибку, если это FAIL ситуация. Можно глянуть доку на тему, когда вообще `results` бывает `null`.

2018-11-10 22:15 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +        if (items == null || items.isEmpty()) {
1) Соответственно, раз `null` нельзя прокидывать, то он тут и не придёт никогда.
2) У тебя список помечен, как `@NonNull`, а ты его проверяешь всё равно. Среда не подчёркивает это ворнингом?) А то косяк.

2018-11-10 22:15 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/model/NewsItem.java
> +    public boolean isUS() {
Я бы только назвал это как-то чуть более развёрнуто, типа `isUsNews` или `hasUsSection` или `hasUsCategory`.

2018-11-11 10:47 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +        if (items == null || items.isEmpty()) {
Неа, не подчеркивает. Может из-за того, что на 3.2 не перешел до сих пор.

2018-11-11 11:58 UTC, merged