Implement ex-6(Persistency)
AlexHurray/NYTimes pull request #5
Opened 2018-11-12 20:53 UTC by AlexHurray

Только пока вместо скриншота приложения, просто экран заставки
![image](https://user-images.githubusercontent.com/37106193/48374356-a5ddd000-e6d5-11e8-8b43-384c96715556.png)
![image](https://user-images.githubusercontent.com/37106193/48374388-bd1cbd80-e6d5-11e8-8ce4-9e7b38dad908.png)
![image](https://user-images.githubusercontent.com/37106193/48374486-17b61980-e6d6-11e8-95e8-59d6b09349da.png)
![image](https://user-images.githubusercontent.com/37106193/48374403-d32a7e00-e6d5-11e8-9d28-015647d011e7.png)
![image](https://user-images.githubusercontent.com/37106193/48374509-27356280-e6d6-11e8-9720-e82c7c0b7f06.png)

2018-11-29 23:46 UTC, colriot requested changes
Есть замечания, просмотри, плз

2018-11-29 23:46 UTC, colriot commented on app/src/main/AndroidManifest.xml
> +            android:noHistory="true" />
А почему в `true`?

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/AppDelegate.java
> +public class AppDelegate extends Application {
Это по сути не делегат, это твоя реализация приложения. Обычно называют с суффиксом Application (как с Activity и Fragment) или App

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/AppDatabase.java
> +}
Потерял строку

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/NewsDao.java
> +    Observable<NewsItem> getNewsById(int id);
Похоже. что тут нужен `Maybe`, т.к. результат либо будет один, либо пусто

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/di/DbModule.java
> +                .build();
Какое-то странное выравнивание - можно спутать метод цепочки с аргументом предыдущего метода

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/di/DbModule.java
> +}
Не забывай

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/NewsRepository.java
> +            newsDao.delete(id);
А сразу там `Completable` в Dao не хочешь сделать?

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/di/NetworkModule.java
> +}
;)

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
> +    NewsRepository repository;
А что тут делает репозиторий?

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
> +    NewsRepository repository;
Во-первых, он не используется в коде. Во-вторых, вью напрямую не работает с данными, только через презентер

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsPresenter.java
> +        Disposable disposable = repository.deleteItem(id)
Операции асинхронные, а ты на это никак не реагируешь, выполняешь их как синхронные. Нужна индикация бы.

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsPresenter.java
> +    public void getNews(int id) {
Этот метод у тебя зависит от параметра. А `delete` уже от того, что было загружено в `getNews`. Т.е метод `getNews` не просто достаёт новости, но и сохраняет их временно, инициализирует контекст. Надо бы это в названии отразить - что это не просто get. Например, init...

И в тоже время отразить то, что загрузка опциональна

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsPresenter.java
> +            view.setData(newsItem);
Ты тут полагаешься на то, что `id` будет соответствовать, но АПИ класса это никак не форсит. Т.ч я бы проверял явно

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsPresenter.java
> +            view.close(R.string.error_delete_in_db);
Почему удаление закрывает экран? Данные есть для показа, дальше пробовать удалить новость или нажать на редактирование можно, почему бы и нет. Логика непонятна

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsedit/NewsEditPresenter.java
> +        Disposable disposable = repository.saveItem(newsItem)
Тоже асинхронная операция. Нужна индикация в UI. Зачем что-то сохранять, если ты не сможешь это достать из UI?

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsedit/NewsEditPresenter.java
> +        Disposable disposable = repository.saveItem(newsItem)
Проблема с том, как ты данные из UI забираешь - у тебя два круга наматывается. А можно на вызов `saveData` сразу отдавать то, что сохранить нужно. Т.е сразу можно собирать данные и их в параметр этой функции отдавать.

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsedit/NewsEditPresenter.java
> +            view.close(R.string.error_save_in_db);
Опять, зачем закрывать, если не удалось сохранить? Пользователь может повторить ещё раз, а ты ему всё закроешь и сотрёшь всё, что он поменял

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +        Disposable disposable = repository.saveData(items)
Лучше бы сохранение вынести на уровень модели. Т.е это не логика презентера - он забрал данные и отобразил, а уже модель/репозиторий должны решать, обновить ли при загрузке данные, если было что-то загружено, то сохранить ли это и тд

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/splash/SplashActivity.java
> +    private CompositeDisposable compositeDisposable = new CompositeDisposable();
Статики на самый верх

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/splash/SplashActivity.java
> +        sharedPreferences.edit().putBoolean(KEY_LOGO, !showLogo).apply();
Типа, у тебя каждый второй раз сплеш будет показан?)

2018-11-29 23:46 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/splash/SplashActivity.java
> +            NewsListActivity.start(this);
А почему тут не через `startSecondActivity`?

2018-11-29 23:46 UTC, colriot commented on app/src/main/res/layout/activity_news_edit.xml
> +        <TextView
Можно ещё заюзать TextInputLayout, тогда хинт будте автоматически в заголовок превращаться, когда начинаешься что-то вводить. Но это на будущее - тут оставляй.

2018-11-30 09:19 UTC, AlexHurray commented on app/src/main/AndroidManifest.xml
> +            android:noHistory="true" />
Случайно затесалось

2018-11-30 09:20 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/NewsRepository.java
> +            newsDao.delete(id);
я б с радостью, но 
"error: Deletion methods must either return void or return int (the number of deleted rows)."

2018-11-30 09:23 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
> +    NewsRepository repository;
Сорри, забыл удалить

2018-11-30 10:03 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/splash/SplashActivity.java
> +        sharedPreferences.edit().putBoolean(KEY_LOGO, !showLogo).apply();
В ДЗ условие такое. Я бы, конечно, только на 1 запуске показывал...

2018-11-30 10:04 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/splash/SplashActivity.java
> +            NewsListActivity.start(this);
и правда, почему?

2018-11-30 10:05 UTC, AlexHurray commented on app/src/main/res/layout/activity_news_edit.xml
> +        <TextView
Хорошо

2018-11-30 10:37 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/NewsDao.java
> +    Observable<NewsItem> getNewsById(int id);
Если поставить там Maybe, то не будет приходить обновление, когда ты что-то поредактировал на 3 экране. А так все происходит автоматом

2018-11-30 12:35 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsPresenter.java
> +            view.setData(newsItem);
Подробнее, плиз. Что именно ты предлагаешь явно проверить?

2018-11-30 15:02 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/NewsDao.java
> +    Observable<NewsItem> getNewsById(int id);
Я понял тебя, да. Тут же летят автоматом обновления по изменении через Room. Проглядел, глаз зацепился за АПИ

2018-11-30 20:12 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/NewsRepository.java
> +            if (newsList.size() > 0) {
А почему сохраняем только если не пусто? Вдруг как раз пустые валидные данные пришли?

2018-11-30 20:12 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/NewsRepository.java
> +        }).subscribeOn(Schedulers.io())
Выравнивание поехало

2018-11-30 20:12 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
> +    public void showErrorMassage(@IdRes int errorMessage) {
-> mEssage
Из названия складывается ощущение, что всегда будет показана ошибка, а на самом деле есть ещё особое значение

2018-11-30 20:12 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
>      public void close(@IdRes int errorMessage) {
А вот тут наоборот. Из АПИ непонятно, что 1) можно и без ошибки закрыться, 2) зачем для закрытия предавать ошибку. Так же в месте вызова `close(0)` неопнятно, что за magic number передаётся.

Лучше не смешивать ответственность, всё равно есть отдельный метод для ошибки - один для ошибки, другой для закрытия.

2018-11-30 20:12 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsActivity.java
>      public void close(@IdRes int errorMessage) {
А вот тут наоборот. Из АПИ непонятно, что 1) можно и без ошибки закрыться, 2) зачем для закрытия предавать ошибку

2018-11-30 20:12 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsedit/NewsEditPresenter.java
>              view.close(R.string.error_save_in_db);
Не ответил и не поменял ничего. Пропустил?

2018-11-30 20:12 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/NewsRepository.java
> +                .observeOn(AndroidSchedulers.mainThread())
Этот метод, так же, как и остальные не должен знать ничего о потоках, на которых он будет отдавать результат. Вдруг их скомбинировать надо будет, вдруг поток поменять. Вообще у Репозитория никакой завязки на UI быть не должно (в том числе uI-поток). И не надо, чтобы методы в Репо вели себя разнородно на столько - одни возвращают Потоки, другие уже сразу Disposable-ы

2018-11-30 20:12 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsdetails/NewsDetailsPresenter.java
> +            view.setData(newsItem);
Явно бы проверял, что id, который грузить собираешься, соответствует тому айтему, который уже загружен

2018-11-30 20:13 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/splash/SplashActivity.java
> +        sharedPreferences.edit().putBoolean(KEY_LOGO, !showLogo).apply();
Да-да, я это и уточнял. Норм

2018-11-30 20:13 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/splash/SplashActivity.java
> +            NewsListActivity.start(this);
=)

2018-11-30 20:31 UTC, colriot reviewed
Внёс пояснения

2018-11-30 20:31 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +        Disposable disposable = repository.saveData(items);
А вообще, ты меня не понял немного. Я предлагаю вообще всё это сохранение занести в Репо, а так же маппинг из сетевых моделей во внутренние тоже, и загрузки из сети. Раньше было так, потому что не было репы, а только сетевой эндпоинт. Теперь появляется Репо, который инкапсулирует всю работу с данными. Т.е UI только у него данные тянет а он внутри решает, отдать ли сохранённое, или загрузить свежее из сети, потом сохранить это внутри, а потом уже отдать готовое в Презентер (т.е презентер не знает ничего ни о том, было ли сохранение, ни о том, откуда данные вообще

2018-11-30 20:31 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/NewsRepository.java
> +            newsDao.delete(id);
Ага! Багло:   https://issuetracker.google.com/issues/63613835

2018-11-30 20:57 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newsedit/NewsEditPresenter.java
>              view.close(R.string.error_save_in_db);
Пардон, пропустил, да

2018-12-01 15:49 UTC, AlexHurray commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +        Disposable disposable = repository.saveData(items);
Вроде теперь понял.

2018-12-06 11:27 UTC, colriot approved these changes
Гут. Есть мелкие замечания, поправь и мёрж. Обнови ветку следующего задания с учётом изменений в этом и делай следущий PR ;)

2018-12-06 11:27 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/NewsRepository.java
> +        List<NewsItem> items = new ArrayList<>();
Один `final`, другой нет

2018-12-06 11:27 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/ui/newslist/NewsListPresenter.java
> +     private void handleError(Throwable throwable) {
Поехал отступ

2018-12-06 11:27 UTC, colriot commented on app/src/main/java/com/example/ermolaenkoalex/nytimes/db/NewsRepository.java
> +                .flatMapCompletable(this::saveData);
В принципе, теперь-то это не надо оборачивать в `Completable`, можно, например, императивный код написать в `doOnNext`. Но это мелочи сейчас, не надо править.

2018-12-06 11:52 UTC, merged